// array containing all the data for the objects in the solar system

// solar system
exports.solarSystemData = {
  sun: {
    id: "sun",
    name: "Sun",
    parentId: "universe",
    angle: 0,
    orbitalTilt: 0,
    diameter: 250,
    radius: 0,
    speed: 0 * 0.025,
    color: "#FFF048",
    zIndexVariation: 0
  },

  mercury: {
    id: "mercury",
    name: `Mercury`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0.1,
    diameter: 10,
    radius: 150,
    speed: 1 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 100
  },
  venus: {
    id: "venus",
    name: `Venus`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: -0.1,
    diameter: 22,
    radius: 290,
    speed: 0.7 * 0.025,
    color: "#FFCF10",
    zIndexVariation: 200
  },
  earth: {
    id: "earth",
    name: `Earth`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 25,
    radius: 380,
    speed: 0.5 * 0.025,
    color: "#2da8ff",
    zIndexVariation: 300
  },
  moon: {
    id: "moon",
    name: "Moon",
    parentId: "earth",
    angle: 0,
    orbitalTilt: 0.2,
    diameter: 3,
    radius: 50,
    speed: 2 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  mars: {
    id: "mars",
    name: `Mars`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 16,
    radius: 580,
    speed: 0.5 * 0.025,
    color: "#FF5F36",
    zIndexVariation: 400
  },
  phobos: {
    id: "phobos",
    name: "Phobos",
    parentId: "mars",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: -0.2,
    diameter: 4,
    radius: 30,
    speed: 2 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  deimos: {
    id: "deimos",
    name: "Deimos",
    parentId: "mars",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0.1,
    diameter: 3,
    radius: 40,
    speed: 2.9 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 2
  },
  ceres: {
    id: "ceres",
    name: `Ceres`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 5,
    radius: 680,
    speed: 0.8 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 500
  },
  jupiter: {
    id: "jupiter",
    name: `Jupiter`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 100,
    radius: 950,
    speed: 0.3 * 0.025,
    color: "#E8C061",
    zIndexVariation: 600
  },
  io: {
    id: `io`,
    name: `Io`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 5,
    radius: 140,
    speed: 1.9 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  europa: {
    id: `europa`,
    name: `Europa`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4.5,
    radius: 112,
    speed: 1.55 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 2
  },
  ganymede: {
    id: `ganymede`,
    name: `Ganymede`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 6,
    radius: 115,
    speed: 1.4 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 3
  },
  callisto: {
    id: `callisto`,
    name: `Callisto`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4,
    radius: 116,
    speed: 1.5 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 4
  },
  amalthea: {
    id: `amalthea`,
    name: `Amalthea`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 5,
    radius: 119,
    speed: 1.7 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 5
  },
  himalia: {
    id: `himalia`,
    name: `Himalia`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4,
    radius: 123,
    speed: 1.7 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 6
  },
  elara: {
    id: `elara`,
    name: `Elara`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 3,
    radius: 126,
    speed: 2.5 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 7
  },
  pasiphae: {
    id: `pasiphae`,
    name: `Pasiphae`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 5,
    radius: 130,
    speed: 2.3 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 8
  },
  sinope: {
    id: `sinope`,
    name: `Sinope`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4,
    radius: 133,
    speed: 2.5 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 9
  },
  lysithea: {
    id: `lysithea`,
    name: `Lysithea`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 3.5,
    radius: 135,
    speed: 2.45 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 10
  },
  carme: {
    id: `carme`,
    name: `Carme`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4.5,
    radius: 138,
    speed: 1.9 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 11
  },
  ananke: {
    id: `ananke`,
    name: `Ananke`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 5,
    radius: 140,
    speed: 2.6 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 12
  },
  leda: {
    id: `leda`,
    name: `Leda`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 3,
    radius: 143,
    speed: 2.7 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 13
  },
  thebe: {
    id: `thebe`,
    name: `Thebe`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4,
    radius: 144,
    speed: 2.75 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 14
  },
  adrastea: {
    id: `adrastea`,
    name: `Adrastea`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 2.5,
    radius: 145,
    speed: 2.3 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 15
  },
  saturn: {
    id: "saturn",
    name: `Saturn`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 90,
    radius: 1500,
    speed: 0.3 * 0.025,
    color: "#EB931E",
    zIndexVariation: 700
  },
  uranus: {
    id: "uranus",
    name: `Uranus`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 70,
    radius: 1900,
    speed: 0.25 * 0.025,
    color: "#A5EBC0",
    zIndexVariation: 800
  },
  neptune: {
    id: "neptune",
    name: `Neptune`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 65,
    radius: 2300,
    speed: 0.2 * 0.025,
    color: "#1455EB",
    zIndexVariation: 900
  },
  pluto: {
    id: "pluto",
    name: `Pluto`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 5,
    radius: 2700,
    speed: 0.25 * 0.025,
    color: "#BBDAEB",
    zIndexVariation: 1000
  },
  haumea: {
    id: "haumea",
    name: `Haumea`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 4,
    radius: 3000,
    speed: 0.2 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1100
  },
  makemake: {
    id: "makemake",
    name: `Makemake`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 3,
    radius: 3300,
    speed: 0.19 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1200
  },
  eris: {
    id: "eris",
    name: `Eris`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 5,
    radius: 3500,
    speed: 0.15 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1300
  }
};
