// array containing all the data for the objects in the solar system

// solar system
exports.solarSystemData = {
  sun: {
    id: "sun",
    name: "Sun",
    parentId: "universe",
    angle: 0,
    orbitalTilt: 0,
    diameter: 250,
    radius: 0,
    speed: 0 * 0.025,
    color: "#FFF048",
    zIndexVariation: 0
  },
  mercury: {
    id: "mercury",
    name: `Mercury`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0.1,
    diameter: 10,
    radius: 150,
    speed: 1 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 100
  },
  venus: {
    id: "venus",
    name: `Venus`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: -0.1,
    diameter: 22,
    radius: 290,
    speed: 0.7 * 0.025,
    color: "#FFCF10",
    zIndexVariation: 200
  },
  earth: {
    id: "earth",
    name: `Earth`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 25,
    radius: 450,
    speed: 0.5 * 0.025,
    color: "#2da8ff",
    zIndexVariation: 300
  },
  moon: {
    id: "moon",
    name: "Moon",
    parentId: "earth",
    angle: 0,
    orbitalTilt: 0.2,
    diameter: 3,
    radius: 50,
    speed: 2 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  mars: {
    id: "mars",
    name: `Mars`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 16,
    radius: 650,
    speed: 0.5 * 0.025,
    color: "#FF5F36",
    zIndexVariation: 400
  },
  phobos: {
    id: "phobos",
    name: "Phobos",
    parentId: "mars",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: -0.2,
    diameter: 4,
    radius: 30,
    speed: 2 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  deimos: {
    id: "deimos",
    name: "Deimos",
    parentId: "mars",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0.1,
    diameter: 3,
    radius: 40,
    speed: 2.9 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 2
  },
  ceres: {
    id: "ceres",
    name: `Ceres`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 5,
    radius: 750,
    speed: 0.8 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 500
  },
  jupiter: {
    id: "jupiter",
    name: `Jupiter`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 100,
    radius: 950,
    speed: 0.3 * 0.025,
    color: "#E8C061",
    zIndexVariation: 600
  },
  io: {
    id: `io`,
    name: `Io`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random() * 0.1,
    diameter: 5,
    radius: 140,
    speed: 1.9 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  europa: {
    id: `europa`,
    name: `Europa`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4.5,
    radius: 112,
    speed: 1.55 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 2
  },
  ganymede: {
    id: `ganymede`,
    name: `Ganymede`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random() * 0.5,
    diameter: 6,
    radius: 115,
    speed: 1.4 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 3
  },
  callisto: {
    id: `callisto`,
    name: `Callisto`,
    parentId: `jupiter`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4,
    radius: 116,
    speed: 1.5 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 4
  },
  // amalthea: {
  //   id: `amalthea`,
  //   name: `Amalthea`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -1,
  //   diameter: 5,
  //   radius: 119,
  //   speed: 1.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 5
  // },
  // himalia: {
  //   id: `himalia`,
  //   name: `Himalia`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -0.5,
  //   diameter: 4,
  //   radius: 123,
  //   speed: 1.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 6
  // },
  // elara: {
  //   id: `elara`,
  //   name: `Elara`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.3,
  //   diameter: 3,
  //   radius: 126,
  //   speed: 2.5 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 7
  // },
  // pasiphae: {
  //   id: `pasiphae`,
  //   name: `Pasiphae`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random(),
  //   diameter: 5,
  //   radius: 130,
  //   speed: 2.3 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 8
  // },
  // sinope: {
  //   id: `sinope`,
  //   name: `Sinope`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random(),
  //   diameter: 4,
  //   radius: 133,
  //   speed: -2.5 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 9
  // },
  // lysithea: {
  //   id: `lysithea`,
  //   name: `Lysithea`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.4,
  //   diameter: 3.5,
  //   radius: 135,
  //   speed: -2.45 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 10
  // },
  // carme: {
  //   id: `carme`,
  //   name: `Carme`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -0.4,
  //   diameter: 4.5,
  //   radius: 138,
  //   speed: 1.9 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 11
  // },
  // ananke: {
  //   id: `ananke`,
  //   name: `Ananke`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.8,
  //   diameter: 5,
  //   radius: 140,
  //   speed: 2.6 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 12
  // },
  // leda: {
  //   id: `leda`,
  //   name: `Leda`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.1,
  //   diameter: 3,
  //   radius: 143,
  //   speed: 2.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 13
  // },
  // thebe: {
  //   id: `thebe`,
  //   name: `Thebe`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -1,
  //   diameter: 4,
  //   radius: 144,
  //   speed: 2.75 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 14
  // },
  // adrastea: {
  //   id: `adrastea`,
  //   name: `Adrastea`,
  //   parentId: `jupiter`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.7,
  //   diameter: 2.5,
  //   radius: 145,
  //   speed: 2.3 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 15
  // },
  saturn: {
    id: "saturn",
    name: `Saturn`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 90,
    radius: 1500,
    speed: 0.3 * 0.025,
    color: "#EB931E",
    zIndexVariation: 700
  },
  mimas: {
    id: `mimas`,
    name: `Mimas`,
    parentId: `saturn`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random() * 0.1,
    diameter: 5,
    radius: 140,
    speed: 1.9 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  enceladus: {
    id: `enceladus`,
    name: `Enceladus`,
    parentId: `saturn`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4.5,
    radius: 112,
    speed: 1.55 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 2
  },
  tethys: {
    id: `tethys`,
    name: `Tethys`,
    parentId: `saturn`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random() * 0.5,
    diameter: 6,
    radius: 115,
    speed: 1.4 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 3
  },
  dione: {
    id: `dione`,
    name: `Dione`,
    parentId: `saturn`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4,
    radius: 116,
    speed: 1.5 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 4
  },
  // rhea: {
  //   id: `rhea`,
  //   name: `Rhea`,
  //   parentId: `saturn`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -1,
  //   diameter: 5,
  //   radius: 119,
  //   speed: 1.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 5
  // },
  // titan: {
  //   id: `titan`,
  //   name: `Titan`,
  //   parentId: `saturn`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -0.5,
  //   diameter: 4,
  //   radius: 123,
  //   speed: 1.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 6
  // },
  // hyperion: {
  //   id: `hyperion`,
  //   name: `Hyperion`,
  //   parentId: `saturn`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.3,
  //   diameter: 3,
  //   radius: 126,
  //   speed: 2.5 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 7
  // },
  // iapetus: {
  //   id: `iapetus`,
  //   name: `Iapetus`,
  //   parentId: `saturn`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random(),
  //   diameter: 5,
  //   radius: 130,
  //   speed: 2.3 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 8
  // },
  // phoebe: {
  //   id: `phoebe`,
  //   name: `Phoebe`,
  //   parentId: `saturn`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random(),
  //   diameter: 4,
  //   radius: 133,
  //   speed: -2.5 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 9
  // },
  // janus: {
  //   id: `janus`,
  //   name: `Janus`,
  //   parentId: `saturn`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.4,
  //   diameter: 3.5,
  //   radius: 135,
  //   speed: -2.45 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 10
  // },
  uranus: {
    id: "uranus",
    name: `Uranus`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 70,
    radius: 1900,
    speed: 0.25 * 0.025,
    color: "#A5EBC0",
    zIndexVariation: 800
  },
  ariel: {
    id: `ariel`,
    name: `Ariel`,
    parentId: `uranus`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random() * 0.1,
    diameter: 5,
    radius: 140,
    speed: 1.9 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  umbriel: {
    id: `umbriel`,
    name: `Umbriel`,
    parentId: `uranus`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4.5,
    radius: 112,
    speed: 1.55 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 2
  },
  titania: {
    id: `titania`,
    name: `Titania`,
    parentId: `uranus`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random() * 0.5,
    diameter: 6,
    radius: 115,
    speed: 1.4 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 3
  },
  // oberon: {
  //   id: `oberon`,
  //   name: `Oberon`,
  //   parentId: `uranus`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random(),
  //   diameter: 4,
  //   radius: 116,
  //   speed: 1.5 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 4
  // },
  // miranda: {
  //   id: `miranda`,
  //   name: `Miranda`,
  //   parentId: `uranus`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -1,
  //   diameter: 5,
  //   radius: 119,
  //   speed: 1.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 5
  // },
  // cordelia: {
  //   id: `cordelia`,
  //   name: `Cordelia`,
  //   parentId: `uranus`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -0.5,
  //   diameter: 4,
  //   radius: 123,
  //   speed: 1.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 6
  // },
  // ophelia: {
  //   id: `ophelia`,
  //   name: `Ophelia`,
  //   parentId: `uranus`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.3,
  //   diameter: 3,
  //   radius: 126,
  //   speed: 2.5 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 7
  // },
  neptune: {
    id: "neptune",
    name: `Neptune`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 65,
    radius: 2300,
    speed: 0.2 * 0.025,
    color: "#7B95EB",
    zIndexVariation: 900
  },
  triton: {
    id: `triton`,
    name: `Triton`,
    parentId: `neptune`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random() * 0.1,
    diameter: 5,
    radius: 140,
    speed: 1.9 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  nereid: {
    id: `nereid`,
    name: `Nereid`,
    parentId: `neptune`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 4.5,
    radius: 112,
    speed: 1.55 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 2
  },
  // naiad: {
  //   id: `naiad`,
  //   name: `Naiad`,
  //   parentId: `neptune`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * 0.5,
  //   diameter: 6,
  //   radius: 115,
  //   speed: 1.4 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 3
  // },
  // thalassa: {
  //   id: `thalassa`,
  //   name: `Thalassa`,
  //   parentId: `neptune`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random(),
  //   diameter: 4,
  //   radius: 116,
  //   speed: 1.5 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 4
  // },
  // despina: {
  //   id: `despina`,
  //   name: `Despina`,
  //   parentId: `neptune`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -1,
  //   diameter: 5,
  //   radius: 119,
  //   speed: 1.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 5
  // },
  pluto: {
    id: "pluto",
    name: `Pluto`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 8,
    radius: 2700,
    speed: 0.25 * 0.025,
    color: "#BBDAEB",
    zIndexVariation: 1000
  },
  charon: {
    id: `charon`,
    name: `Charon`,
    parentId: `pluto`,
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: Math.random(),
    diameter: 3,
    radius: 30,
    speed: 1.5 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1
  },
  // nix: {
  //   id: `nix`,
  //   name: `Nix`,
  //   parentId: `pluto`,
  //   angle: Math.floor(Math.random() * 360),
  //   orbitalTilt: Math.random() * -1,
  //   diameter: 2,
  //   radius: 45,
  //   speed: 1.7 * 0.025,
  //   color: "#FFE7D6",
  //   zIndexVariation: 2
  // },
  haumea: {
    id: "haumea",
    name: `Haumea`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 7,
    radius: 3000,
    speed: 0.2 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1100
  },
  makemake: {
    id: "makemake",
    name: `Makemake`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 7,
    radius: 3300,
    speed: 0.19 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1200
  },
  eris: {
    id: "eris",
    name: `Eris`,
    parentId: "sun",
    angle: Math.floor(Math.random() * 360),
    orbitalTilt: 0,
    diameter: 7,
    radius: 3500,
    speed: 0.15 * 0.025,
    color: "#FFE7D6",
    zIndexVariation: 1300
  }
};
